### ISSUE TITLE
Review Application

### ISSUE THREAD

**Issue by dboghrat** [Imageomics/BeetlePalooza-2024#1]
@sydnerecord @hlapp @sokole @ramirezmichelle Please review the BeetlePalooza application: [https://docs.google.com/forms/d/1LA0rvYkotA0JMh2_2xuaDdzruE6_EAFJNk9oydC8FCc/edit]

**Comment by sydnerecord** [comment]
Almost done. Just need to have final approval by the organizing committee. I also need to update the link for the CFP once it is finalized by the committee.
