### ISSUE TITLE
Review/Edit Data & Code Policy

### ISSUE THREAD

**Issue by dboghrat** [Imageomics/BeetlePalooza-2024#3]
Review and update the Data & Code Policy from Image Datapalooza [https://docs.google.com/document/d/1qVxA0rtDyoTzc6ruirrC8_836ZdzMDauIipUL1bYthE/edit?usp=sharing]

**Comment by hlapp** [comment]
I think this will be superseded by our Digital Product policy, which actually evolved from the Image Datapalooza policy.

**Comment by hlapp** [comment]
Policy posted: https://github.com/Imageomics/BeetlePalooza-2024/wiki/Product-Licensing-and-Release-Policy
